### ISSUE TITLE
Cannot restart gateway after killing it

### ISSUE THREAD

**Issue by piotrnar** [humblenginr/goocoin#5]
Kill the gateway and try to quickly start it again, you will get an errro:

```
Establishing connection with  192.168.0.85:8878 ...
panic: failed to WebSocket dial: expected handshake response status code 101 but got 403

goroutine 1 [running]:
main.main()
        /home/user/gocoin/remote-wallet/gateway/main.go:30 +0x508
```

Wait a bit longer and it will eventually start.

**Comment by humblenginr** [comment]
fixed in https://github.com/piotrnar/gocoin/pull/68/commits/8d97a810890564f9d95771954ca78aa0959f576a
