### ISSUE TITLE
WebUI reports "Incorrect Sequence value" when signing a transaction

### ISSUE THREAD

**Issue by piotrnar** [humblenginr/goocoin#6]
Using with the latest WebUI, trying to sign a transaction with the default sequence (-3), we get an error "Incorrect Sequence value"

Recently there was a change around checking the sequence number, that has not been ported to the sign_transaction() function (in  webui/sendtx.go)

Perhaps the best solution would be to combine sign_transaction() and dl_payment() to use a common code.
Otherwise, the change in checking the sequence number needs to be applied to the sign_transaction()

**Comment by piotrnar** [comment]
If you end up merging the two function into one, please clean up the code in a way that there would be a minimal change (minimal number of lines changed/deleted/added) between the original files and the new ones required for the remote wallet functionality.

Because of the short deadline, I think we have to abandon the Server Sent Events approach and just focus on freezing the functionality and cleaning up the code. Therefore also please remove any code related to that - anything that isn't being used (worth saving it for later though).

**Comment by humblenginr** [comment]
Fixed in https://github.com/piotrnar/gocoin/pull/68/commits/d97edeed801b58338a4a6d861ea218a63dca7814

**Comment by humblenginr** [comment]
I have extracted the common functionality between two functions into a separate function.

**Comment by humblenginr** [comment]
> Because of the short deadline, I think we have to abandon the Server Sent Events approach and just focus on freezing the functionality and cleaning up the code. Therefore also please remove any code related to that - anything that isn't being used (worth saving it for later though).

SSE is already in place. It is how we are pushing notification to the UI on successful signing of the transaction.

**Comment by piotrnar** [comment]
Very well
