### ISSUE TITLE
WebSocket server only binds to a localhost

### ISSUE THREAD

**Issue by piotrnar** [humblenginr/goocoin#8]
Because of it, connections from remote "wallets" (gateways) are not possible.

Easy fix is to change WebsocketServerAddr to just ":8878"  - in client/usif/webui/webui.go

Also, there is the same name "WebsocketServerAddr" used in both client/usif/webui/webui.go and remote-wallet/common/config.go

I would advise to rename one of them as these are not the same things and it is confusing now.

**Comment by humblenginr** [comment]
fixed in https://github.com/piotrnar/gocoin/pull/68/commits/7fd8ff1b2a2a85783c8987083b0fd436a65f3e9a
